### ISSUE TITLE
Multi-Page Printing Broken with body height 100%

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#83]
Apparently setting body height to 100% breaks printing (can only print the first page).  (body height auto seems to fix it)

I removed `!important` from that one line from `gform_bootstrap.min.js` in a pretty janky way, but this will need to be resolved somehow correctly.

I also added this to the Binghamton Graphene CSS:
```css
@media print {
    body {
        height: auto !important;
    }
}
```

> Sorry if this is operator error, but the last few days I am not able to print all of the exception form, only page 1. I have fixed the setup and it still won’t work. Thoughts?
